#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - ufw
  - fail2ban
  - certbot
  - python3-certbot-nginx
  - git
  - rsync

users:
  - name: deploy
    groups: sudo, www-data
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - "${ssh_public_key}"

write_files:
  # SSH hardening
  - path: /etc/ssh/sshd_config.d/99-security.conf
    content: |
      PasswordAuthentication no
      PubkeyAuthentication yes
      PermitRootLogin no
      Protocol 2
      MaxAuthTries 3

runcmd:
  # Basic firewall setup
  - ufw --force reset
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw --force enable

  # Start services
  - systemctl enable nginx
  - systemctl start nginx
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - systemctl restart sshd

  # Create ready marker for GitHub Actions
  - echo "$(date): Basic server setup complete" > /home/deploy/server-ready.log
  - chown deploy:deploy /home/deploy/server-ready.log
