name: Deploy Static Website

on:
  push:
    branches: [main, master]
    paths:
      - "static/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH with ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "🔍 Testing SSH connection to $SERVER_HOST..."
          ssh -o ConnectTimeout=10 -o BatchMode=yes $SERVER_USER@$SERVER_HOST "echo '✅ SSH connection successful'"

      - name: Deploy static files
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          echo "🚀 Deploying static files to $SERVER_HOST"

          # Create backup first
          ssh $SERVER_USER@$SERVER_HOST "
            sudo cp -r /var/www/$DOMAIN_NAME /var/www/${DOMAIN_NAME}_backup_$(date +%Y%m%d_%H%M%S) 2>/dev/null || echo 'No existing files to backup'
          "

          # Sync static files to server
          rsync -avz --delete \
            --exclude='.DS_Store' \
            --exclude='Thumbs.db' \
            --exclude='.git*' \
            ./static/ $SERVER_USER@$SERVER_HOST:/var/www/$DOMAIN_NAME/

          echo "✅ Files deployed successfully"

      - name: Fix file permissions
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          ssh $SERVER_USER@$SERVER_HOST "
            sudo chown -R deploy:www-data /var/www/$DOMAIN_NAME/ &&
            sudo chmod -R 755 /var/www/$DOMAIN_NAME/ &&
            sudo find /var/www/$DOMAIN_NAME/ -type f -exec chmod 644 {} \;
          "

      - name: Test deployment
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "🔍 Testing deployment..."

          # Wait for changes to propagate
          sleep 5

          # Test website is accessible
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://$DOMAIN_NAME)
          if [ $HTTP_STATUS -eq 200 ]; then
            echo "✅ Website is accessible (HTTP $HTTP_STATUS)"
          else
            echo "❌ Website test failed (HTTP $HTTP_STATUS)"
            # Don't fail the build for this, might be temporary
          fi

          # Optional: Run post-deploy check on server
          ssh $SERVER_USER@$SERVER_HOST "./post-deploy-check.sh" || echo "⚠️ Post-deploy check script not available"

      - name: Deployment summary
        run: |
          echo "🎉 Deployment completed!"
          echo "📍 Website: https://${{ secrets.DOMAIN_NAME }}"
          echo "🕐 Deployed at: $(date)"
          echo "📦 Commit: ${{ github.sha }}"
